[package]
name = "keybear-core"
version = "0.1.0"
authors = ["Thomas Versteeg <thomas@versteeg.email>"]
license = "AGPL-3.0-or-later"
edition = "2018"
readme = "README.md"
repository = "https://github.com/keybear/keybear"
description = "Core methods & primitives for a Keybear client/server"
include = ["src/**/*", "LICENSE", "README.md"]

[features]
actix = ["actix-web", "futures", "futures-util"] # allow direct usage in an actix server

[dependencies]
actix-web = { version = "3.3.2", optional = true }
anyhow = "1.0.36"
chacha20poly1305 = "0.7.1"
futures = { version = "0.3.8", optional = true }
futures-util = { version = "0.3.8", optional = true }
log = "0.4.11"
rand_core = { version = "0.5.0", default-features = false }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
x25519-dalek = "1.1.0"

[dev-dependencies]
tempfile = "3.1.0"
